# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\view\mainwindow_FaceRecognition.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 877)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Main_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.Main_groupBox.setTitle("")
        self.Main_groupBox.setObjectName("Main_groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Main_groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttons_groupBox = QtWidgets.QGroupBox(self.Main_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttons_groupBox.sizePolicy().hasHeightForWidth())
        self.buttons_groupBox.setSizePolicy(sizePolicy)
        self.buttons_groupBox.setMinimumSize(QtCore.QSize(241, 776))
        self.buttons_groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.buttons_groupBox.setTitle("")
        self.buttons_groupBox.setObjectName("buttons_groupBox")
        self.loadimages_pushButton = QtWidgets.QPushButton(self.buttons_groupBox)
        self.loadimages_pushButton.setGeometry(QtCore.QRect(30, 30, 182, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.loadimages_pushButton.setFont(font)
        self.loadimages_pushButton.setObjectName("loadimages_pushButton")
        self.webcam_radioButton = QtWidgets.QRadioButton(self.buttons_groupBox)
        self.webcam_radioButton.setGeometry(QtCore.QRect(40, 80, 123, 27))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.webcam_radioButton.setFont(font)
        self.webcam_radioButton.setAutoFillBackground(False)
        self.webcam_radioButton.setIconSize(QtCore.QSize(16, 16))
        self.webcam_radioButton.setChecked(True)
        self.webcam_radioButton.setObjectName("webcam_radioButton")
        self.loadvideo_pushButton = QtWidgets.QPushButton(self.buttons_groupBox)
        self.loadvideo_pushButton.setGeometry(QtCore.QRect(30, 150, 182, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.loadvideo_pushButton.setFont(font)
        self.loadvideo_pushButton.setObjectName("loadvideo_pushButton")
        self.video_radioButton = QtWidgets.QRadioButton(self.buttons_groupBox)
        self.video_radioButton.setGeometry(QtCore.QRect(40, 110, 76, 27))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.video_radioButton.setFont(font)
        self.video_radioButton.setObjectName("video_radioButton")
        self.horizontalLayout.addWidget(self.buttons_groupBox)
        self.webcam_groupBox = QtWidgets.QGroupBox(self.Main_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webcam_groupBox.sizePolicy().hasHeightForWidth())
        self.webcam_groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.webcam_groupBox.setFont(font)
        self.webcam_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.webcam_groupBox.setFlat(False)
        self.webcam_groupBox.setObjectName("webcam_groupBox")
        self.Web_label_2 = QtWidgets.QLabel(self.webcam_groupBox)
        self.Web_label_2.setGeometry(QtCore.QRect(10, 33, 781, 751))
        self.Web_label_2.setText("")
        self.Web_label_2.setObjectName("Web_label_2")
        self.horizontalLayout.addWidget(self.webcam_groupBox)
        self.gridLayout.addWidget(self.Main_groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1101, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadimages_pushButton.setText(_translate("MainWindow", "Загрузить личность"))
        self.webcam_radioButton.setText(_translate("MainWindow", "Веб-камера"))
        self.loadvideo_pushButton.setText(_translate("MainWindow", "Загрузить видео"))
        self.video_radioButton.setText(_translate("MainWindow", "Видео"))
        self.webcam_groupBox.setTitle(_translate("MainWindow", "Веб-камера"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
